/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssignmentsTab: typeof import('./src/components/Courses/tabs/AssignmentsTab.vue')['default']
    CourseCenter: typeof import('./src/components/Courses/CourseCenter.vue')['default']
    CourseDetail: typeof import('./src/components/Courses/CourseDetail.vue')['default']
    CourseHeader: typeof import('./src/components/Courses/CourseHeader.vue')['default']
    Courses: typeof import('./src/components/Courses/Courses.vue')['default']
    CourseStats: typeof import('./src/components/Courses/CourseStats.vue')['default']
    CourseTabs: typeof import('./src/components/Courses/CourseTabs.vue')['default']
    DiscussionsTab: typeof import('./src/components/Courses/tabs/DiscussionsTab.vue')['default']
    ExamsTab: typeof import('./src/components/Courses/tabs/ExamsTab.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    FunctionButtons: typeof import('./src/components/tools/FunctionButtons.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LoginView: typeof import('./src/components/login/LoginView.vue')['default']
    Note: typeof import('./src/components/note/note.vue')['default']
    Notifications: typeof import('./src/components/Notifications/Notifications.vue')['default']
    RecommendedCourses: typeof import('./src/components/Courses/RecommendedCourses.vue')['default']
    ResourcesTab: typeof import('./src/components/Courses/tabs/ResourcesTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Todos: typeof import('./src/components/tools/Todos.vue')['default']
    UserCenter: typeof import('./src/components/user/UserCenter.vue')['default']
    UserEvaluation: typeof import('./src/components/user/UserEvaluation.vue')['default']
    UserMessage: typeof import('./src/components/user/UserMessage.vue')['default']
    VideoPlayerModal: typeof import('./src/components/Courses/VideoPlayerModal.vue')['default']
    VideosTab: typeof import('./src/components/Courses/tabs/VideosTab.vue')['default']
  }
}
